### ISSUE TITLE
ZendRouter integration is incompatible with HHVM

### ISSUE THREAD

**Issue by Naktibalda** [zendframework/zend-expressive-zendrouter#14]
Since https://github.com/zendframework/zend-expressive-zendrouter/commit/22adad805b1ef04e1ce1fb0374f31535a6947e09 ZendExpressive fails on HHVM with `Fatal error: Arrays are not allowed in class constants in /.../zendframework/zend-expressive-zendrouter/src/ZendRouter.php on line 33`

https://travis-ci.org/zendframework/zend-expressive-zendrouter/jobs/184049213#L340

[AuraRouter](https://travis-ci.org/zendframework/zend-expressive-aurarouter/jobs/184396719#L290) and [FastRoute](https://travis-ci.org/zendframework/zend-expressive-fastroute/jobs/184034729#L277) integrations have the same issue.

**Comment by weierophinney** [comment]
Arrays have been allowed as class constant values since PHP 5.6.0; HHVM needs to update to allow this; they [already have an issue open for it](https://github.com/facebook/hhvm/issues/4277).
