### ISSUE TITLE
Zend\Expressive\Route will not accept anything other than objects implementing the MiddlewareInterface starting in version 3.0.0

### ISSUE THREAD

**Issue by spencer237** [zendframework/zend-expressive-zendrouter#45]
Hello everyone please i have this problem :
we detected usage of "callable" for path "/nkenmoe" using methods GET. Please update your code to create middleware instances implementing MiddlewareInterface; use decorators for callable middleware if needed. in C:\xampp\htdocs\mon_mvc\vendor\zendframework\zend-expressive-router\src\Route.php on line 296

**Comment by weierophinney** [comment]
Can you provide a sample of code that results in this error, please, so we can provide you with a solution?

If you are calling `new Route(. . .)`, the answer is pretty simple: you will need to decorate your callable middleware using one of either `Zend\Stratigility\middleware()` or `Zend\Stratigility\doublePassMiddleware()` when you provide it to the constructor. Which one is necessary will depend on the signature of the callable you are using.

**Comment by spencer237** [comment]
Thanks @weierophinney i'm try
