### ISSUE TITLE
Default parameter do not work

### ISSUE THREAD

**Issue by IgorDePaula** [zendframework/zend-expressive-zendrouter#8]
how as https://zend-expressive.readthedocs.io/en/latest/cookbook/using-routed-middleware-class-as-controller/

This do no work for zend-router. Using the zend-router I need put default values on url plugin view. Without this default values, I got 500 error, without exit message on console. If I put default value for ID parameter like 0, stay strange on index page, or datagrid page.

**Comment by weierophinney** [comment]
Can you please see if the official documentation yields a different result,
please?

## 

https://docs.zendframework.com/zend-expressive/cookbook/using-routed-middleware-class-as-controller/

Thanks!

**Comment by IgorDePaula** [comment]
Yes, I read the documentation and I got the same result.

2016-06-25 21:01 GMT-03:00 weierophinney notifications@github.com:

**Comment by geerteltink** [comment]
@IgorDePaula Can you show some code?

If you only get a 500 error on your screen, you might want to use something like [whoops](https://docs.zendframework.com/zend-expressive/features/error-handling/#whoops) during development.

That example code is for fastroute. If you use that exact path config `'/album[/{action:add|edit}[/{id}]]'` it starts throwing errors about a missing translator. The path config that is working for me for zend-router is `'/album[/:action[/:id]]'`. I've also tried generating the URL's with the router and they all seem to work.

This is the route for zend-router:

``` php
        [
            'name'            => 'album',
            'path'            => '/album[/:action[/:id]]',
            'middleware'      => App\Action\AlbumPage::class,
            'allowed_methods' => ['GET'],
            'options' => [
                'defaults' => [
                    'action' => 'index',
                ]
            ]
        ],
```

**Comment by IgorDePaula** [comment]
I trying this form, but in url appear the action default and id default
parameters, is strange. In zf2 this not happens.

My code:

https://gist.github.com/IgorDePaula/ca9048e602f15d1a6c5a3eb4c471e308
https://gist.github.com/IgorDePaula/cc418f72f234fe800caf273f9e19bdcf

2016-06-26 4:54 GMT-03:00 Geert Eltink notifications@github.com:

**Comment by IgorDePaula** [comment]
I got a workaround for this question, more one for this framework. Thank you for your help.
